#!/bin/bash
#Menu
echo ""
echo -e "\033[01;34mList คำสั่งที่ใช้กับ vps เครื่องนี้เท่านั้น \033[0m"
echo " ------------------------------- "
echo -e " "
echo -e "* m    : List of menu "
echo -e "* a    : Create SSH & OpenVPN"
echo -e "* anp  : Create SSH & OpenVPN with user & pass"
echo -e "* t    : new trial user"
echo -e "* rn   : chang pass & day"
echo -e "* d    : delete user SSH & OpenVPN"
echo -e "* s    : view all member online  OpenVPN"
echo -e "* h    : view all member online SSH"
echo -e "* k    : view all member SSH & OpenVPN"
echo -e "* dx   : Delete User Expired"
echo -e "* b    : Banned User"
echo -e "* ub   : Undo Banned User "
echo -e "* rb   : Reboot vps "
echo -e "* exit:  Close juicessh"
echo -e "* bw   : Show network traffic "
echo -e "* bwd  : Show network traffic of day"
echo -e "* bwm  : Show network traffic of month"
echo -e "* srh  : Set remote & host"
echo -e "* rerh : Reset remote & host"
echo -e "* speedtest : Speedtest VPS"  
echo -e "* cex  : Show User coming Expire"
echo -e ""
echo " ------------------------------- "
echo ""
echo -e "\033[01;35mพิมพ์คำสั่ง ตามเมนูข้างบนเท่านั้น  \033[0m"
echo ""
echo " ------------------------------- "
echo ""